config/routes.rb
Washoes2::Application.routes.draw do
  devise_for :users
  root to: "rules#index"
  resources :players
  resources :games
  resources :brackets

  get "/rules", to: "rules#index", as: "rules"
  post "/set_winner", to: "games#set_winner", as: "set_winner"
  

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :game_players, dependent: :destroy

  has_many :players, through: :game_players
  belongs_to :winner, class_name: "Player"
  belongs_to :bracket

  accepts_nested_attributes_for :game_players

  default_scope order(:id)

  def set_winner(player)
    self.winner = player
    if self.save
      return true
    else
      return false
    end
  end

  def to_a
    output = []

    if self.game_players.first.player_id
      output << self.game_players.first.player.name
      output << self.game_players.first.player.bracket_points(self.bracket)
    else
      output << "???"
      output << "?"
    end
    
    if self.game_players.last.player_id
      output << self.game_players.last.player.name
      output << self.game_players.last.player.bracket_points(self.bracket)
    else
      output << "???"
      output << "?"
    end

    return output
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @games = Game.all
    @game = Game.new
  end

  def show
    @game = Game.find(params[:id])
    @point = Point.new
    @game_form = Game.new

    check_winner
  end

  def new
    @game = Game.new
    @game.game_players.build
    @game.game_players.build

  end

  def create
    @game = Game.new(game_params)
    @game.game_players.each do |game_player|
      game_player.points.build
    end

    if @game.save
      redirect_to games_path, flash: {notice: "Game was created."}
    else
      render :new
    end
  end

  def update
    @game = Game.find(params[:id])
    if (params[:points][:score1]).length == 0 || (params[:points][:score2]).length == 0
      redirect_to game_path(@game), flash: { error: "Both points must be populated." }
    else
      @game.game_players[0].points << Point.create(score: params[:points][:score1])
      @game.game_players[1].points << Point.create(score: params[:points][:score2])

      redirect_to game_path(@game), flash: {notice: "Game updated."}
    end
  end

  def check_winner #End of Round win check
    @points_a = @game.game_players[0]
    @points_b = @game.game_players[1]

    if @points_a.total == 21 && @points_b.total == 21 || @points_a.total > 63 && @points_b.total > 63 #sudden death instance.
      @points_a = []
      @points_b = []
      #redirect_to sudden_death
    elsif @points_a.total == 21 || @points_b.total > 63
      @game.winner = @game.players[0]
      @game.save
    elsif @points_b.total == 21 || @points_a.total > 63
      @game.winner = @game.players[1]
      @game.save
    end
  end

  def set_winner
    @player = Player.find(params[:player])
    @game = Game.find(params[:game])
    if @game.set_winner(@player)
      redirect_to game_path(@game), flash: {notice: "#{@player.name} was set as winner for Game ID: #{@game.id}"}
    else
      redirect_to game_path(@game), flash: {error: "#{@player.name} was NOT set as winner for Game ID: #{@game.id}"}
    end
  end
  
  def destroy
    Game.find(params[:id]).destroy
    
    redirect_to games_path, flash: {notice: "Game was deleted."}
  end

  private

  def game_params
    params.require(:game).permit(game_players_attributes: [:player_id])
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_errors.html.erb
<% @game.errors.full_messages.each do |message| %>
  <%= message %><br>
<% end %><br>

app/views/games/_flash.html.erb
<% if flash[:error] %>
  <font color="red"><%= flash[:error] %></font><br><br>
<% end %>
<% if flash[:notice] %>
  <font color="green"><%= flash[:notice] %></font><br><br>
<% end %>

app/views/games/_form.html.erb
<%= form_for @game do |f| %>

  

  <div id="error_explanation">
      <% if @game.errors.any? %>
        <%= render "errors", object: f.object %>
      <% end %>
  </div>

  <%= f.fields_for :game_players do |ff| %>
    <%= ff.collection_select :player_id, Player.all, :id, :name %><br>
  <% end %>

  <%= f.submit nil, :class => 'btn btn-primary'   %>
<% end %>

app/views/games/_game.html.erb
<% pos = pos %>
<% game_name = game_name %>

<% if game.game_players.first.player_id && game.game_players.last.player_id %>
  <%= link_to "#{game_name}", game %>
<% else %>
  <%= game_name %>
<% end %>
<br>  
<% if game.game_players.first.player_id %>
  <% if !game.winner %>
  <!-- do nothing -->
  <% elsif game.winner == game.game_players.first.player %>
    <b>
  <% elsif game.winner == game.game_players.last.player %>
    <span class="loser">
  <% end %>
  <%= game.game_players.first.player.name %> <%= "(#{game.game_players.first.player.bracket_points(game.bracket)})" %></span></b>
<% else %>
  <%= "??? (?)" %>
<% end %>

<% if pos == "left" %>
<%= "vs." %><br>
<% else %>
<br><%= "vs." %>
<% end %>

<% if game.game_players.last.player_id %>
  <% if game.winner == game.game_players.last.player %>
    <b>
  <% elsif game.winner == game.game_players.first.player %>
    <span class="loser">
  <% end %>
  <%= game.game_players.last.player.name %> <%= "(#{game.game_players.last.player.bracket_points(game.bracket)})" %><span class="white"><%= "." %></span></b>
<% else %>
  <%= "??? (?)" %><span class="white"><%= "." %></font>
<% end %> 

app/views/games/index.html.erb
<h2>Games</h2>
<%= render "flash" %>
<%= link_to "New Game", new_game_path %><br><br>
<table border="1" cellpadding="2" width="300px" cellspacing="0">
  <tr><td>Game</td><td>Players</td><td>Bracket</td><td></td></tr>
<% @games.each do |game| %>
  <tr>
    <td>ID: <% if game.game_players.count == 2 %><%= link_to "#{game.id}", game_path(game) %><% else %><%= game.id %><% end %></td>
    <td>
      
      <table border="0" cellpadding="0" width="150px" cellspacing="1">
        
        <% game.players.each do |player| %>
          <tr>
            <td>
              <li><%= player.name %></li>
            </td>
            <td><% if !game.winner %>
                  <%= form_for @game, url: set_winner_path do |f| %>
                  <%= hidden_field_tag(:player, player.id) %>
                  <%= hidden_field_tag(:game, game.id) %>
                  <%= f.submit "W" %>
                <% end %>
            </td>
          </tr>
        <% end %>
<% end %>
          
        <tr>
          <td>
                  <li>Winner: <% if game.winner %>
                        <%= game.winner.name %>
                      <% end %></li>
          </td>
        </tr>
      </table>

    </td>
    <td><center><%= game.bracket.name %></center></td>
    <td><center><%= link_to "Delete", game, data: { confirm: "Are you sure?" }, method: :delete %></center></td>
  </tr>
<% end %>
</table>

app/views/games/new.html.erb
<h2>Add new game:</h2>
<%= render "flash" %>
<%= render "form" %>

app/views/games/show.html.erb
<h3>Game ID: <%= "#{@game.id}" %></h3>
<b>Points:</b>
<table border="0" cellpadding="2" cellspacing="0  ">
  <tr valign="top">
    <td align="top">
      <table border="1" cellpadding="2" cellspacing="0">
        <% @game.game_players.each do |game_player| %>
        <tr>
          <td><%= game_player.player.name %> <font size=1px>(<%= game_player.player.bracket_points(game_player.bracket) %>):</font> </td>

            <% if !@game.winner %>
            <td>
                  <%= form_for @game_form, as: :post, url: set_winner_path do |f| %>
                  <%= hidden_field_tag(:player, game_player.player.id) %>
                  <%= hidden_field_tag(:game, @game.id) %>
                  <%= f.submit "W", :class => 'btn btn-primary'   %>
                <% end %>
            </td>
            <% end %>
            

          <% game_player.points.each do |point| %>
            <% if point.score %>
              <td><center><%= point.score %></center></td>
            <% end %>
          <% end %>
          <td>Total: <%= game_player.total %></td>
        </tr>
        <% end %>
      </table>
    </td>
    <td>
      <% if !@game.winner %>
        <%= form_for @game do |f| %>
          <%= text_field :points, :score1, autofocus: true, :autocomplete => :off %><br>
          <%= text_field :points, :score2, :autocomplete => :off %><br>
          <%= f.submit nil, :class => 'btn btn-primary' %>
        <% end %>
      <% end %>
    </td>
  </tr>
</table>
<br>
<% if @game.winner %>
  <b>Winner:</b>
  <li><%= @game.winner ? "#{@game.winner.name}" : "" %> </li>
  <br>
<% end %>

<%= link_to "Back to Bracket", bracket_path(@game.bracket) %>