config/routes.rb
Washoes2::Application.routes.draw do
  devise_for :users
  root to: "rules#index"
  resources :players
  resources :games
  resources :brackets

  get "/rules", to: "rules#index", as: "rules"
  post "/set_winner", to: "games#set_winner", as: "set_winner"
  

end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :game_players, dependent: :destroy

  has_many :games, through: :game_players
  has_many :brackets, through: :game_players

  belongs_to :user

  validates :name, :presence => { :message => " is required." }
  validates_uniqueness_of :name, :scope => :user_id

  # def user_name_uniqueness(name)
  #   @players = Players.all
  #   @players.each do |player|
  #     if player.name == name && player.user == current_user
  #       errors.add_to_base('Current user already has a Player with this name.')
  #     end
  #   end
  # end
  
  def wins
    Game.where(winner: self).length
  end

  def bracket_wins
    Bracket.where(winner: self).length
  end

  def bracket_points(bracket)
    points = []
    self.game_players.each do |game_player|
      if game_player.bracket == bracket
        points << game_player.total_points
      end
    end
    total = points.reduce(0, :+)
    return total
  end

  def lifetime_points
    points = []
    self.game_players.each do |game_player|
      points << game_player.total_points
    end
    total = points.reduce(0, :+)
    return total
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_user!

  def index
    @players = current_user.players
    @players = @players.sort_by { |hsh| hsh[:name] }
  end

  def show
    @player = Player.find(params[:id])
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new player_params
    @player.user = current_user

    if @player.save #If it can save, redirects to movie path, otherwise renders new page again (and errors are displayed)
      redirect_to players_path, flash: {success: "Player was created."}
    else
      render :new
    end
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])

    if @player.update_attributes(player_params) #If it can save, redirects to movie path, otherwise renders new page again (and errors are displayed)
      redirect_to players_path, flash: {success: "Player was updated."}
    else
      render :edit
    end
  end

  def destroy
    Player.find(params[:id]).destroy
    
    redirect_to players_path, flash: {success: "Player was deleted."}
  end

  # def picks
  #   @players = Player.all
  # end

  def player_params
    params.require(:player).permit(:name, :wins)
  end

end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_errors.html.erb
<% @player.errors.full_messages.each do |message| %>
  <%= message %><br>
<% end %><br>

app/views/players/_form.html.erb
<%= form_for @player do |f| %>

<div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, autofocus: true %>
</div>

<div id="error_explanation">
    <% if @player.errors.any? %>
      <%= render "errors", object: f.object %>
    <% end %>
</div>

  <%= f.submit class: 'btn btn-primary'  %>
<% end %>

app/views/players/edit.html.erb
<h2>Edit player:</h2>
<%= render "form" %>

app/views/players/index.html.erb
<h2>Players:</h2>
<% if flash[:success] %>
  <%= flash[:success] %><br><br>
<% end %>
<%= link_to "New Player", new_player_path %><br><br>

<% if @players.length > 0 %>
  <table border="1" cellpadding="2" width="550px" cellspacing="0">
    <tr><td>Name:</td><td>Lifetime Wins:</td><td>Bracket Wins:</td><td>Lifetime Points:</td><td></td><td></td></tr>
  <% @players.each do |player| %>
    <tr>
    <td><%= link_to "#{player.name}", player_path(player) %> </td><td><%= player.wins %> </td><td><%= player.bracket_wins %> </td><td><%= player.lifetime_points %></td><td> <center><%= link_to "Edit", edit_player_path(player) %> </center></td><td> <center><% if player.brackets == [] %><%= link_to "Delete", player, data: { confirm: "Are you sure?" }, method: :delete %><% else %>Delete<% end %></center></td>
    </tr>
  <% end %>
  </table>
<% else %>
  You have no Players! Create one now...
  <br>
<% end %>
<br>

app/views/players/new.html.erb
<h2>Add new player:</h2>
<%= render "form" %>

app/views/players/show.html.erb
<h2><%= @player.name %> <%= "(ID: #{@player.id})" %></h2>
Lifetime Wins: <%= @player.wins %><br>
Bracket Wins: <%= @player.bracket_wins %><br>
Lifetime Points: <%= @player.lifetime_points %>